"""
WealthIQ Portfolio Templates & Screeners
Pre-built diversified portfolio recommendations + TradingView-style screeners.
"""

PORTFOLIO_TEMPLATES = [
    {
        "id": "top200",
        "name": "WealthIQ 200",
        "description": "Concentrated exposure to the 200 largest US companies by market cap. The market's most established names.",
        "stocks": 200,
        "sectors": 11,
        "risk": "Medium",
        "holdings": ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META", "TSLA", "AVGO", "JPM", "UNH"],
        "allocation": {"Tech": 35, "Healthcare": 15, "Finance": 13, "Consumer": 12, "Industrial": 10, "Energy": 8, "Other": 7},
    },
    {
        "id": "top500",
        "name": "WealthIQ 500",
        "description": "Broad exposure to the 500 largest US companies by market cap. The standard benchmark for overall market performance.",
        "stocks": 500,
        "sectors": 11,
        "risk": "Medium",
        "holdings": ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META", "TSLA", "AVGO", "JPM", "V"],
        "allocation": {"Tech": 30, "Healthcare": 13, "Finance": 13, "Consumer": 11, "Industrial": 9, "Energy": 5, "Other": 19},
    },
    {
        "id": "dividend_kings",
        "name": "Dividend Kings",
        "description": "Companies that have increased dividends for 50+ consecutive years. Maximum income stability and reliability.",
        "stocks": 30,
        "sectors": 8,
        "risk": "Low",
        "holdings": ["JNJ", "KO", "PG", "PEP", "MMM", "ABT", "EMR", "CL", "ITW", "GD"],
        "allocation": {"Consumer": 30, "Industrial": 25, "Healthcare": 20, "Finance": 10, "Energy": 8, "Other": 7},
    },
    {
        "id": "high_yield",
        "name": "High Yield Income",
        "description": "Top dividend-paying stocks and REITs for maximum current income. 4%+ average yield across holdings.",
        "stocks": 25,
        "sectors": 6,
        "risk": "Low",
        "holdings": ["VZ", "T", "MO", "PM", "OKE", "KMI", "O", "VICI", "EPD", "ET"],
        "allocation": {"Telecom": 20, "REITs": 25, "Energy": 20, "Consumer": 15, "Utilities": 12, "Other": 8},
    },
    {
        "id": "growth_tech",
        "name": "Tech Growth",
        "description": "High-growth technology and AI companies positioned for the next decade. Higher risk, higher potential reward.",
        "stocks": 20,
        "sectors": 3,
        "risk": "High",
        "holdings": ["NVDA", "MSFT", "GOOGL", "META", "AMZN", "AVGO", "AMD", "CRM", "PLTR", "SNOW"],
        "allocation": {"AI/Cloud": 40, "Semiconductors": 30, "Software": 20, "Other": 10},
    },
    {
        "id": "conservative_60_40",
        "name": "Conservative 60/40",
        "description": "Classic balanced portfolio: 60% stocks, 40% bonds. Designed for capital preservation with moderate growth.",
        "stocks": 5,
        "sectors": 3,
        "risk": "Low",
        "holdings": ["VTI", "VXUS", "BND", "AGG", "VIG"],
        "allocation": {"US Stocks": 40, "Intl Stocks": 20, "US Bonds": 25, "Intl Bonds": 15},
    },
    {
        "id": "global_diversified",
        "name": "Global Diversified",
        "description": "Worldwide exposure across US, Europe, Asia and emerging markets. True geographic diversification.",
        "stocks": 40,
        "sectors": 11,
        "risk": "Medium",
        "holdings": ["AAPL", "MSFT", "ASML", "TSM", "SONY", "BABA", "RY", "UL", "VALE", "INFY"],
        "allocation": {"US": 45, "Europe": 20, "Asia": 20, "Emerging": 10, "Canada": 5},
    },
    {
        "id": "esg_sustainable",
        "name": "ESG Sustainable",
        "description": "Companies with top environmental, social and governance scores. Invest with impact and returns.",
        "stocks": 30,
        "sectors": 8,
        "risk": "Medium",
        "holdings": ["MSFT", "GOOGL", "CRM", "ADBE", "NEE", "ENPH", "TSLA", "NVO", "UNH", "PG"],
        "allocation": {"Tech": 30, "Clean Energy": 20, "Healthcare": 15, "Consumer": 15, "Industrial": 10, "Other": 10},
    },
    {
        "id": "retiree_income",
        "name": "Retiree Income",
        "description": "Designed for retirees: stable income, low volatility, capital preservation. 3-5% annual yield target.",
        "stocks": 15,
        "sectors": 5,
        "risk": "Low",
        "holdings": ["BND", "VYM", "SCHD", "O", "JNJ", "PG", "KO", "VZ", "JEPI", "AGG"],
        "allocation": {"Bonds": 40, "Dividend Stocks": 30, "REITs": 15, "Utilities": 10, "Cash": 5},
    },
    {
        "id": "aggressive_growth",
        "name": "Aggressive Growth",
        "description": "Maximum growth potential for long-term investors. Small-cap + high-beta names with 5+ year horizon.",
        "stocks": 20,
        "sectors": 5,
        "risk": "High",
        "holdings": ["PLTR", "SOFI", "COIN", "RBLX", "DKNG", "HOOD", "ARM", "SMCI", "MARA", "IONQ"],
        "allocation": {"Fintech": 25, "AI/Tech": 30, "Crypto": 20, "Gaming": 15, "Other": 10},
    },
]

SCREENERS = {
    "stocks": {
        "label": "Stocks",
        "description": "Screen US stocks by market cap, sector, performance",
        "filters": ["sector", "market_cap", "pe", "beta", "dividend_yield", "return_1y"],
    },
    "etfs": {
        "label": "ETFs",
        "description": "Screen ETFs by category, yield, expense ratio",
        "filters": ["category", "yield", "return_1y", "risk"],
    },
    "dividends": {
        "label": "Dividends",
        "description": "Find highest-yielding dividend stocks",
        "filters": ["country", "yield_min", "growth_rate", "payout_ratio"],
    },
    "low_risk": {
        "label": "Low Risk",
        "description": "Conservative picks with stable returns",
        "filters": ["max_beta", "min_yield", "max_risk_score"],
    },
    "high_growth": {
        "label": "High Growth",
        "description": "Momentum stocks with strong returns",
        "filters": ["min_return_1y", "sector", "market_cap_min"],
    },
    "value": {
        "label": "Value",
        "description": "Undervalued stocks with low P/E ratios",
        "filters": ["max_pe", "min_dividend", "sector"],
    },
}
